stages:
  load_data:
    cmd: python src/01_load_and_save_data.py --config=params.yaml
    deps:
      - src/01_load_and_save_data.py
      - src/utils/common_utils.py
    params:
      - data_source.source_path
      - artifacts.raw_local_data
    outs:
      - artifacts/raw_local_data_dir/data.csv
  
  split_data:
    cmd: python src/02_split_data.py --config=params.yaml
    deps:
      - src/02_split_data.py
      - src/utils/common_utils.py
      - artifacts/raw_local_data_dir/data.csv
    params:
      - base.random_state
      - base.test_size
      - artifacts.raw_local_data
      - artifacts.split_data.processed_data_dir
      - artifacts.split_data.train_data
      - artifacts.split_data.test_data
    outs:
      - artifacts/processed_data/train.csv
      - artifacts/processed_data/test.csv

  train:
    cmd: python src/03_train.py --config=params.yaml
    deps:
      - src/03_train.py
      - artifacts/processed_data/train.csv
      - src/utils/common_utils.py
    params:
      - base.random_state
      - base.target
      - artifacts.split_data.train_data
      - estimators.ElasticNet.params.alpha
      - estimators.ElasticNet.params.l1_ratio
    metrics: 
      - artifacts/report/params.json:
          cache: false
    outs:
      - artifacts/saved_models/model.joblib   

  evaluate:
    cmd: python src/04_evaluate.py --config=params.yaml
    deps:
      - src/04_evaluate.py
      - artifacts/processed_data/test.csv
      - artifacts/saved_models/model.joblib
      - src/utils/common_utils.py
    params:
      - base.target
      - artifacts.split_data.test_data
    metrics: 
      - artifacts/report/scores.json:
          cache: false