base:
    project: 'simple-dvc-ml-pipeline'
    test_size: 0.2
    random_state: 42
    target: 'quality'


data_source:
    source_path: C:/Users/acreddy/Desktop/wine/winequality-red.csv


artifacts:
    artifacts_dir: artifacts

    
    raw_local_data_dir: artifacts/raw_local_data_dir
    raw_local_data: artifacts/raw_local_data_dir/data.csv


    split_data:
        processed_data_dir: artifacts/processed_data
        train_data: artifacts/processed_data/train.csv
        test_data: artifacts/processed_data/test.csv


        

  



